package com.amar.slackclone.search;
import com.amar.slackclone.search.dto.SearchPageResponse;import com.amar.slackclone.search.dto.SearchPageResponse.SearchHit;import com.amar.slackclone.channel.*;import com.amar.slackclone.message.*;import com.amar.slackclone.conversation.*;import com.amar.slackclone.workspace.*;import com.amar.slackclone.user.*;import org.springframework.data.domain.PageRequest;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service public class SearchService{private final UserRepository users;private final WorkspaceMemberRepository memberships;private final ChannelRepository channels;private final MessageRepository messages;private final ConversationMessageRepository conversationMessages;private final ConversationService conversations;
public SearchService(UserRepository users,WorkspaceMemberRepository memberships,ChannelRepository channels,MessageRepository messages,ConversationMessageRepository conversationMessages,ConversationService conversations){this.users=users;this.memberships=memberships;this.channels=channels;this.messages=messages;this.conversationMessages=conversationMessages;this.conversations=conversations;}
@Transactional(readOnly=true) public SearchPageResponse search(String query,SearchType type,Long workspaceId,int page,int requestedSize,String email){String term=query.trim();int size=Math.min(requestedSize,50);if(term.length()<2)return new SearchPageResponse(term,page,size,false,List.of());User me=users.findByEmailIgnoreCase(email).orElseThrow();Set<Long>workspaceIds=new HashSet<>(memberships.findAllByUserId(me.getId()).stream().map(x->x.getWorkspace().getId()).toList());if(workspaceId!=null)workspaceIds.retainAll(Set.of(workspaceId));List<Channel> visible=workspaceIds.stream().flatMap(id->channels.findVisibleChannels(id,me.getId()).stream()).toList();int needed=Math.min((page+1)*size+1,501);List<SearchHit> all=new ArrayList<>();
if(type==SearchType.ALL||type==SearchType.MESSAGES){Set<Long>channelIds=new HashSet<>(visible.stream().map(Channel::getId).toList());if(!channelIds.isEmpty())messages.searchAccessible(channelIds,term,PageRequest.of(0,needed)).stream().map(m->new SearchHit(m.getId(),"CHANNEL_MESSAGE",m.getSender().getDisplayName(),snippet(m.getContent()),"#"+m.getChannel().getName(),m.getChannel().getWorkspace().getId(),m.getChannel().getId(),null,m.getCreatedAt(),m.getThreadRootMessage()==null?null:m.getThreadRootMessage().getId())).forEach(all::add);if(workspaceId==null)conversationMessages.searchAccessible(me.getId(),term,PageRequest.of(0,needed)).stream().map(m->new SearchHit(m.getId(),"CONVERSATION_MESSAGE",m.getSender().getDisplayName(),snippet(m.getContent()),"Conversation",null,null,m.getConversation().getId(),m.getCreatedAt(),m.getThreadRootMessage()==null?null:m.getThreadRootMessage().getId())).forEach(all::add);}
if(type==SearchType.ALL||type==SearchType.CHANNELS)visible.stream().filter(c->contains(c.getName(),term)).map(c->new SearchHit(c.getId(),"CHANNEL","#"+c.getName(),c.isArchived()?"Archived channel":"Channel",c.getWorkspace().getName(),c.getWorkspace().getId(),c.getId(),null,null,null)).limit(needed).forEach(all::add);
if(type==SearchType.ALL||type==SearchType.PEOPLE)memberships.findMessageableUsers(me.getId()).stream().filter(u->contains(u.getDisplayName(),term)||contains(u.getUsername(),term)||contains(u.getEmail(),term)).map(u->new SearchHit(u.getId(),"USER",u.getDisplayName(),"@"+u.getUsername(),"Person",null,null,null,null,null)).limit(needed).forEach(all::add);
if((type==SearchType.ALL||type==SearchType.CONVERSATIONS)&&workspaceId==null)conversations.list(email).stream().filter(c->contains(c.displayName(),term)).map(c->new SearchHit(c.id(),"CONVERSATION",c.displayName(),c.type().name(),"Conversation",null,null,c.id(),null,null)).limit(needed).forEach(all::add);
if(type==SearchType.MESSAGES)all.sort(Comparator.comparing(SearchHit::timestamp,Comparator.nullsLast(Comparator.reverseOrder())));int from=Math.min(page*size,all.size()),to=Math.min(from+size,all.size());return new SearchPageResponse(term,page,size,to<all.size(),List.copyOf(all.subList(from,to)));}
private boolean contains(String value,String term){return value!=null&&value.toLowerCase(Locale.ROOT).contains(term.toLowerCase(Locale.ROOT));}private String snippet(String value){return value.length()>180?value.substring(0,180)+"…":value;}}
