package com.amar.slackclone.search;
import com.amar.slackclone.channel.*;import com.amar.slackclone.message.*;import com.amar.slackclone.user.*;import com.amar.slackclone.workspace.*;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.transaction.annotation.Transactional;
import java.time.Instant;import static org.junit.jupiter.api.Assertions.*;
@SpringBootTest @Transactional class SearchServiceIntegrationTests{
@Autowired SearchService search;@Autowired UserRepository users;@Autowired WorkspaceRepository workspaces;@Autowired WorkspaceMemberRepository memberships;@Autowired ChannelRepository channels;@Autowired MessageRepository messages;
private User member;private Workspace workspace;
@BeforeEach void setup(){String suffix=String.valueOf(System.nanoTime());member=users.save(new User("search"+suffix+"@example.com","hash","Search User",Instant.now(),Instant.now()));workspace=workspaces.save(new Workspace("Search Team","search-"+suffix,member,Instant.now(),Instant.now()));memberships.save(new WorkspaceMember(workspace,member,WorkspaceRole.OWNER,Instant.now()));}
@Test void filtersPaginatesAndDoesNotLeakPrivateChannelMessages(){Channel visible=channel("results",false),secret=channel("secret",true);message(visible,"needle one");message(visible,"needle two");message(visible,"needle three");message(secret,"needle secret");var first=search.search("needle",SearchType.MESSAGES,workspace.getId(),0,2,member.getEmail());assertEquals(2,first.results().size());assertTrue(first.hasNext());assertTrue(first.results().stream().allMatch(hit->hit.channelId().equals(visible.getId())));var second=search.search("needle",SearchType.MESSAGES,workspace.getId(),1,2,member.getEmail());assertEquals(1,second.results().size());assertFalse(second.hasNext());assertTrue(search.search("results",SearchType.CHANNELS,workspace.getId(),0,20,member.getEmail()).results().stream().allMatch(hit->hit.type().equals("CHANNEL")));}
private Channel channel(String name,boolean privateChannel){Channel value=new Channel();value.setWorkspace(workspace);value.setName(name);value.setSlug(name+System.nanoTime());value.setCreatedBy(member);value.setPrivateChannel(privateChannel);return channels.save(value);}private void message(Channel channel,String content){Message value=new Message();value.setChannel(channel);value.setSender(member);value.setContent(content);messages.save(value);}}
