spring.application.name=slack-clone-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/slack_clone_db
spring.datasource.username=slack_user
spring.datasource.password=slack_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jackson.time-zone=UTC

app.jwt.secret=c2xhY2stY2xvbmUtZGV2ZWxvcG1lbnQtand0LXNlY3JldC1rZXktMjAyNi1hbWFyLXNlY3VyZQ==
app.jwt.expiration-ms=86400000
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
app.upload.directory=uploads
