spring.application.name=slack-clone-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/slack_clone_db
spring.datasource.username=slack_user
spring.datasource.password=slack_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jackson.time-zone=UTC
